'use strict';
const { withDeadline } = require('./policy');
function normalizeProviderError(error, response) { const status = response?.status; const e = error instanceof Error ? error : new Error(String(error || 'provider error')); e.code = e.name === 'AbortError' || /deadline|timeout/i.test(e.message) ? 'PROVIDER_TIMEOUT' : (status ? `PROVIDER_HTTP_${status}` : 'PROVIDER_ERROR'); e.status = status; return e; }
function authValue(auth) { return typeof auth === 'function' ? auth() : auth; }
async function requestDashScope(input, options = {}) {
  const fetchImpl = options.fetch || globalThis.fetch; if (typeof fetchImpl !== 'function') throw new Error('fetch is required');
  const endpoint = (typeof options.endpoint === 'function' ? options.endpoint(input) : options.endpoint) || process.env.DASHSCOPE_BASE_URL || 'https://dashscope.aliyuncs.com/compatible-mode/v1';
  const key = await authValue(options.authLookup || options.apiKey || process.env.DASHSCOPE_API_KEY); if (!key) throw new Error('provider auth unavailable');
  const deadline = withDeadline(options.signal, options.timeoutMs || 25000); const normalizedEndpoint = String(endpoint).replace(/\/$/, ''); const url = normalizedEndpoint.endsWith('/chat/completions') ? normalizedEndpoint : `${normalizedEndpoint}/chat/completions`;
  try { const response = await fetchImpl(url, { method: 'POST', headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json', ...(options.headers || {}) }, body: JSON.stringify(input.body || input), signal: deadline.signal }); if (!response.ok) { const text = await response.text().catch(() => ''); deadline.cancel(); throw normalizeProviderError(new Error(text.slice(0, 500) || `HTTP ${response.status}`), response); } response.__cancelDeadline = deadline.cancel; return response; } catch (error) { deadline.cancel(); throw normalizeProviderError(error); }
}
async function executeDashScope(input, options = {}) { const response = await requestDashScope(input, options); try { const data = await response.json(); const choice = data?.choices?.[0]; return { text: choice?.message?.content || choice?.text || '', raw: data, usage: data?.usage || null, model: data?.model || input.body?.model || input.model }; } finally { response.__cancelDeadline?.(); } }
async function streamDashScope(input, options = {}) { const response = await requestDashScope(input, options); try { if (!response.body || typeof response.body.getReader !== 'function') return { text: (await executeJson(response)).text, usage: null, model: input.body?.model || input.model }; const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = '', text = '', usage = null; for (;;) { const part = await reader.read(); if (part.done) break; buffer += decoder.decode(part.value, { stream: true }); const lines = buffer.split(/\r?\n/); buffer = lines.pop() || ''; for (const line of lines) { const value = line.replace(/^data:\s*/, '').trim(); if (!value || value === '[DONE]') continue; try { const data = JSON.parse(value); text += data?.choices?.[0]?.delta?.content || data?.choices?.[0]?.message?.content || ''; if (data.usage) usage = data.usage; } catch (_) {} } } return { text, usage, model: input.body?.model || input.model }; } finally { response.__cancelDeadline?.(); } }
async function executeJson(response) { const data = await response.json(); return { text: data?.choices?.[0]?.message?.content || '', raw: data, usage: data?.usage || null }; }
module.exports = { requestDashScope, executeDashScope, streamDashScope, normalizeProviderError };
