const {
  SCENE_EVIDENCE_FINGERPRINT,
  SCENE_EVIDENCE_VERSION,
} = require('./sceneEvidenceRegistryV4');

const CLOUD_BUILD_VERSION = 'generateOutfit-scene-evidence-v4-20260810';
const CANDIDATE_POOL_ENGINE_VERSION = `generateOutfit-scene-evidence-v4-${SCENE_EVIDENCE_FINGERPRINT}`;
const REASON_CATALOG_VERSION = 'eligibility-reason-v6';
const AI_REVIEW_VERSION = 'stylist-review-v3';

module.exports = {
  AI_REVIEW_VERSION,
  CANDIDATE_POOL_ENGINE_VERSION,
  CLOUD_BUILD_VERSION,
  REASON_CATALOG_VERSION,
  SCENE_EVIDENCE_FINGERPRINT,
  SCENE_EVIDENCE_VERSION,
};
