const assert = require('node:assert/strict');
const test = require('node:test');

const {
  XIAODA_CONTENT_PLAN_VERSION,
  buildXiaodaContentPlanV1,
  buildXiaodaDefaultReviewV1,
  hasQualifiedAiReviewIncrementV1,
  normalizeXiaodaSuggestionV1,
  renderXiaodaPlanTextV1,
} = require('./xiaodaContentPlan');

function outfit(overrides = {}) {
  return {
    outfitKey: 'top_bottom_shoes',
    scene: '上班',
    sceneIntent: 'work:walkable',
    primaryBenefit: 'walkable_commute',
    secondaryBenefit: 'temperature_buffer',
    weatherSnapshot: { temp: 18, weather: '多云' },
    outfitItemRoles: [
      { id: 'top', slot: 'top', role: 'core', displayName: '白衬衫' },
      { id: 'bottom', slot: 'bottom', role: 'core', displayName: '黑色长裤' },
      { id: 'shoes', slot: 'shoes', role: 'core', displayName: '乐福鞋' },
    ],
    snapshotItems: [
      { itemId: 'top', category: 'top', name: '白衬衫' },
      { itemId: 'bottom', category: 'bottom', name: '黑色长裤' },
      { itemId: 'shoes', category: 'shoes', name: '乐福鞋' },
    ],
    ...overrides,
  };
}

function visible(plan) {
  return [
    ...renderXiaodaPlanTextV1(plan).bodyParagraphs,
    renderXiaodaPlanTextV1(plan).suggestion?.text,
  ].filter(Boolean).join('\n');
}

test('content plan has stable structure, item roles and default readable copy', () => {
  const plan = buildXiaodaContentPlanV1(outfit());
  const text = renderXiaodaPlanTextV1(plan);

  assert.equal(plan.version, XIAODA_CONTENT_PLAN_VERSION);
  assert.equal(plan.sceneIntent, 'work:walkable');
  assert.deepEqual(plan.items.map((item) => item.role), ['core', 'core', 'core']);
  assert.ok(text.bodyParagraphs.length > 0);
  assert.doesNotMatch(visible(plan), /\b(top|bottom|shoes|outerwear|accessory|onepiece|category|subcategory|slot)\b/i);
});

test('suggestion is hidden when it lacks a grounded target action and object', () => {
  const noSuggestion = buildXiaodaContentPlanV1(outfit({ primaryBenefit: 'clean_daily', secondaryBenefit: '' }));
  const vague = normalizeXiaodaSuggestionV1('想再明确一点，可以调整一下。', noSuggestion);

  assert.equal(noSuggestion.suggestion, null);
  assert.equal(vague, null);
  assert.equal(renderXiaodaPlanTextV1(noSuggestion).suggestion, null);
});

test('grounded suggestion names the target action and real object', () => {
  const plan = buildXiaodaContentPlanV1(outfit({
    secondaryBenefit: 'temperature_buffer',
    outfitItemRoles: [
      { id: 'top', slot: 'top', role: 'core', displayName: '白衬衫' },
      { id: 'bottom', slot: 'bottom', role: 'core', displayName: '黑色长裤' },
      { id: 'shoes', slot: 'shoes', role: 'core', displayName: '乐福鞋' },
      { id: 'coat', slot: 'outerwear', role: 'functional', displayName: '薄外套' },
    ],
  }));

  assert.ok(plan.suggestion);
  assert.match(plan.suggestion.text, /薄外套/);
  assert.match(plan.suggestion.text, /带|拿|穿|换|留/);
});

test('default review and AI review use the same plan and only AI with information gain replaces it', () => {
  const plan = buildXiaodaContentPlanV1(outfit());
  const fallback = buildXiaodaDefaultReviewV1(plan);
  const emptyAi = {
    reason: '白衬衫和黑色长裤很日常，想再明确一点也可以。',
    tip: '想再明确一点，可以调整一下。',
    source: 'ai',
  };
  const usefulAi = {
    reason: '这套可以把白衬衫作为干净的上半身重点，黑色长裤负责压住通勤感，乐福鞋让走动时也不显得太随意。',
    tip: '如果今天走动比较多，可以保留乐福鞋作为主要鞋子，不再临时换不熟悉的新鞋。',
    source: 'ai',
  };

  assert.equal(hasQualifiedAiReviewIncrementV1(emptyAi, plan, fallback).qualified, false);
  assert.equal(hasQualifiedAiReviewIncrementV1(usefulAi, plan, fallback).qualified, true);
});

test('old cached mechanical comments are not qualified until regenerated by user action', () => {
  const plan = buildXiaodaContentPlanV1(outfit());
  const fallback = buildXiaodaDefaultReviewV1(plan);
  const oldCache = {
    reason: '单品和单品很日常，整体比较完整，场景适配度比较高。',
    tip: '想再明确一点，可以优化配饰。',
    source: 'cached_ai',
  };
  const result = hasQualifiedAiReviewIncrementV1(oldCache, plan, fallback);

  assert.equal(result.qualified, false);
  assert.ok(result.rejectReasons.includes('empty_phrase'));
});

test('four scene families replay at least three batches with distinct content angles', () => {
  const plans = ['home', 'work', 'date', 'sport'].flatMap((scene) =>
    Array.from({ length: 3 }, (_, index) => buildXiaodaContentPlanV1(outfit({
      scene,
      sceneIntent: {
        home: ['home:indoor_relax', 'home:quick_outing', 'home:clean_daily'],
        work: ['work:polished', 'work:walkable', 'work:layered'],
        date: ['date:soft', 'date:highlight', 'date:casual'],
        sport: ['sport:training', 'sport:light_activity', 'sport:walk'],
      }[scene][index],
      primaryBenefit: `${scene}_benefit_${index}`,
      observationFocus: `focus_${index}`,
    }))),
  );
  const keys = plans.map((plan) => `${plan.sceneIntent}|${plan.primaryBenefit}|${plan.observations.join('|')}`);

  assert.equal(plans.length, 12);
  assert.equal(new Set(keys).size, 12);
});
