import type { StorageNamespaceContract } from './core.mjs';

export const STORAGE_BUDGETS = {
  steadyStateTargetBytes: 384 * 1024,
  highWaterBytes: 384 * 1024,
  softLimitBytes: 512 * 1024,
} as const;

export const LOCAL_STORAGE_REGISTRY = {
  'authResume:v2': {
    enabled: true,
    owner: 'Auth',
    classification: 'USER_CRITICAL',
    sourceOfTruth: 'WeChat identity + CloudBase runtime identity',
    crossSessionNeed: 'Resume the last confirmed owner; never authorizes Cloud access',
    recomputable: false,
    ttlMs: null,
    maxEntries: 1,
    maxBytes: 16 * 1024,
    evictable: false,
    evictionPolicy: 'PROTECTED',
    migrationVersion: 2,
  },
  'profileBootstrap:v2': {
    enabled: true,
    owner: 'Profile',
    classification: 'BOOTSTRAP_CACHE',
    sourceOfTruth: 'CloudBase users',
    crossSessionNeed: 'Compact first-paint profile projection',
    recomputable: true,
    ttlMs: 24 * 60 * 60 * 1000,
    maxEntries: 1,
    maxBytes: 32 * 1024,
    evictable: true,
    evictionPolicy: 'EXPIRE_THEN_LRU',
    migrationVersion: 2,
  },
  'weatherLastKnown:v2': {
    enabled: true,
    owner: 'Weather',
    classification: 'BOOTSTRAP_CACHE',
    sourceOfTruth: 'Weather provider + CloudBase server cache',
    crossSessionNeed: '10m fresh and 24h stale-if-error last-known weather',
    recomputable: true,
    ttlMs: 24 * 60 * 60 * 1000,
    staleIfErrorMs: 24 * 60 * 60 * 1000,
    maxEntries: 1,
    maxBytes: 16 * 1024,
    evictable: true,
    evictionPolicy: 'EXPIRE_THEN_LRU',
    migrationVersion: 2,
  },
  'todayBootstrap:v2': {
    enabled: true,
    owner: 'Today',
    classification: 'BOOTSTRAP_CACHE',
    sourceOfTruth: 'recommendation_batches_v2 + canonical Outfit',
    crossSessionNeed: 'Compact first-paint projection',
    recomputable: true,
    ttlMs: 6 * 60 * 60 * 1000,
    maxEntries: 1,
    maxBytes: 96 * 1024,
    evictable: true,
    evictionPolicy: 'EXPIRE_THEN_LRU',
    migrationVersion: 2,
  },
  'wardrobeBootstrap:v2': {
    enabled: true,
    owner: 'Wardrobe',
    classification: 'BOOTSTRAP_CACHE',
    sourceOfTruth: 'CloudBase clothes',
    crossSessionNeed: 'Compact first-page projection',
    recomputable: true,
    ttlMs: 30 * 60 * 1000,
    maxEntries: 1,
    maxBytes: 96 * 1024,
    evictable: true,
    evictionPolicy: 'EXPIRE_THEN_LRU',
    migrationVersion: 2,
  },
  'uploadWorkflow:v2': {
    enabled: true,
    owner: 'Upload workflow',
    classification: 'WORKFLOW_REF',
    sourceOfTruth: 'CloudBase upload_batches/upload_images/clothes_drafts',
    crossSessionNeed: 'Resume references for accepted non-terminal work',
    recomputable: false,
    // 24h is an orphan verification threshold, not an unconditional timer.
    // The workflow store removes a ref only after cloud reconciliation.
    ttlMs: null,
    maxEntries: 1,
    maxBytes: 32 * 1024,
    evictable: false,
    evictionPolicy: 'TERMINAL_DELETE',
    migrationVersion: 2,
  },
  'behaviorPending:v1': {
    // PB-22 guardrail only. Enabling writes requires a separate product decision.
    enabled: false,
    owner: 'Behavior ingestion',
    classification: 'PENDING_QUEUE',
    sourceOfTruth: 'Cloud behavior ingestion after ack',
    crossSessionNeed: 'Future optional bounded unacked queue',
    recomputable: false,
    ttlMs: 72 * 60 * 60 * 1000,
    maxEntries: 50,
    maxBytes: 64 * 1024,
    evictable: false,
    evictionPolicy: 'FIFO_ACKED',
    migrationVersion: 1,
  },
  'storageMeta:v2': {
    enabled: true,
    owner: 'Storage migration',
    classification: 'MIGRATION_META',
    sourceOfTruth: 'Client migration owner',
    crossSessionNeed: 'Versioned migration checkpoints and bounded summaries',
    recomputable: false,
    ttlMs: null,
    maxEntries: 4,
    maxBytes: 16 * 1024,
    evictable: false,
    evictionPolicy: 'PROTECTED',
    migrationVersion: 2,
  },
} as const satisfies Record<string, StorageNamespaceContract>;

export type LocalStorageNamespace = keyof typeof LOCAL_STORAGE_REGISTRY;
